# Test: Basic features - variables, dependencies, parameters

greeting = "Hello"
target = "World"

@default
task hello:
    echo "{{greeting}}, {{target}}!"

task build:
    echo "Building..."

task test: [build]
    echo "Testing after build"

task greet name="Developer":
    echo "Welcome, {{name}}!"

task all: [hello, build, test]
    echo "All done!"
