; File autogenerated by build-queries-nvim.py; do not edit

; This file tells us about the scope of variables so e.g. local
; variables override global functions with the same name

; Scope

(recipe) @local.scope

; Definitions

(assignment
  name: (identifier) @local.definition)

(parameter
  name: (identifier) @local.definition)

(recipe_header
  name: (identifier) @local.definition)

(import_statement
  namespace: (identifier) @local.definition)

; References

(function_call
  name: (identifier) @local.reference)

(dependency
  name: (dependency_name) @local.reference)

(value
  (identifier) @local.reference)
