; File autogenerated by build-queries-nvim.py; do not edit

; Outline for Jake - Symbol navigation and document structure
;
; This enables:
; - Document outline / symbol tree in editors
; - Breadcrumb navigation
; - Go to symbol functionality
;
; Captures:
;   @name    - The symbol name to display
;   @item    - The entire definition (for nesting)
;   @context - Keywords that provide context (task, file, etc.)

; Simple recipe: `name:`
(recipe
  (recipe_header
    name: (identifier) @name
  )
) @item

; Task recipe: `task name:`
(recipe
  (recipe_header
    type: "task" @context
    name: (identifier) @name
  )
) @item

; File recipe: `file target.txt:`
(recipe
  (recipe_header
    type: "file" @context
    name: (identifier) @name
  )
) @item

; Variable assignments
(assignment
  name: (identifier) @name
) @item

; Import statements with namespace (only show imports that define a namespace)
(import_statement
  namespace: (identifier) @name
) @item
