; File autogenerated by build-queries-nvim.py; do not edit

; Tags for Jake - Symbol navigation and outline support
;
; This enables:
; - Document outline / symbol tree in editors
; - Go to symbol functionality
; - Breadcrumb navigation
;
; Captures:
;   @name - The symbol name to display
;   @definition.* - Type of definition for categorization

; Recipe definitions (functions in outline)
(recipe
  (recipe_header
    name: (identifier) @name
  )
) @definition.function

; Task recipe with explicit type
(recipe
  (recipe_header
    type: "task"
    name: (identifier) @name
  )
) @definition.function

; File recipe (shown as class/module in outline since it's a build target)
(recipe
  (recipe_header
    type: "file"
    name: (identifier) @name
  )
) @definition.class

; Variable assignments (constants in outline)
(assignment
  name: (identifier) @name
) @definition.constant

; Import statements with namespace
(import_statement
  namespace: (identifier) @name
) @definition.module
